// track-changes-for-angular/src/app/menu/menu.component.ts
/**
 * @license Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import { Component } from '@angular/core';

@Component( {
	selector: 'menu',
	templateUrl: './menu.component.html',
	styleUrls: [ './menu.component.css' ]
} )

export class MenuComponent {}

// track-changes-for-react/src/components/Menu.js
/**
 * @license Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import React from 'react';
import { Link } from 'react-router-dom';

const Menu = () => {
	return (
		<div>
			<h1>Track changes for React</h1>
			<nav>
				<ul>
					<li><Link to="/load-save-integration">Load save integration</Link></li>
					<li><Link to="/track-changes-adapter">Track changes adapter</Link></li>
				</ul>
			</nav>
		</div>
	);
};

export default Menu;
