// revision-history-for-angular/src/main.ts
/**
 * @license Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if ( environment.production ) {
	enableProdMode();
}

platformBrowserDynamic().bootstrapModule( AppModule )
	.catch( err => console.error( err ) );

// revision-history-for-react/src/index.js
/**
 * @license Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './components/App';

const root = createRoot( document.getElementById( 'root' ) );
root.render( <App /> );
